### ISSUE TITLE
Error running Amber in nw.js

### ISSUE THREAD

**Issue by muspellsson** [amber-smalltalk/amber#1166]
Steps to reproduce (I tried on Linux and Windows)

1. Execute "amber init" in some directory
2. Add "main": "index.html" to package.json (as nw.js requires it)
3. Execute "/path/to/nwjs/nw ."

The errors are:

* TypeError: undefined is not a function
    at file:///home/fmjr/rst/the.js:7:17076
* AssertionError: path must be a string
    at Module.require (module.js:355:3)
    at require (module.js:375:17)
    at window.require (<anonymous>:4:17)
    at file:///home/fmjr/rst/index.html:19:7

Either in devel or in deploy mode. Everything works in Chrome and Firefox (opening index.html or 127.0.0.1:4000) and in nw.js with "amber serve".

nw.js version: 0.12.0-alpha3 and node-webkit 0.11.6
amber version: latest

**Comment by herby** [comment]
Must be something with CORS / file:/// not working. Maybe not.
Anyway, you can produce unminified the.js to pinpoint the error better, you should add the proper option (`"optimize": "none"` maybe, it can be found in r.js docs) in Gruntfile.js in the tasks that build the.js in devel/deploy mode.

**Comment by muspellsson** [comment]
It looks like that "require.config" function is undefined in this case.

**Comment by herby** [comment]
Looks strange. How did you come to that conclusion? Did you do the unminified build?

**Comment by muspellsson** [comment]
Yes, I did this build and the error message now points to the the.js:2091:9, where the line "require.config({" is.

**Comment by herby** [comment]
Hm. Well, then it is probably the case. Don't know how can require.config be undefined. Maybe because require is still the node's commonjs require and not the requirejs's amd require which should shadow it.

Ivan Sukin wrote:

**Comment by muspellsson** [comment]
Look like an issue exists for atom-shell too, but not for brackets-shell.

**Comment by futuremint** [comment]
The `require` being referred to in the context of nw.js is _node.js's_ require, _not_ requirejs's require.
You will have to move the built-in pre-defined `require` out of the way to get the default setup for Amber to use requirejs.
