### ISSUE TITLE
Node.js 4.1.0 amber init problem

### ISSUE THREAD

**Issue by adrian-castravete** [amber-smalltalk/amber#1202]
Hello, after updating to the latest node version each time I try to do `amber init` on an empty directory I get this **exception**. I have no idea where this stems from. Any Ideas?

The log:
```
Welcome to Amber version 0.15.0-pre (NodeJS 4.1.0).
AmberCli class >> main
AmberCli class >> handleArguments:
AmberCli class(ProtoObject) >> perform:withArguments:
AmberCli class >> init:
Initer >> start
Initer >> gruntInitThenDo:
Initer >> npmScriptForModule:named:
SmalltalkImage >> readJSObject:
JavaScript exception: TypeError: Cannot read property 'constructor' of null
/home/adrian/.npm-packages/lib/node_modules/amber-cli/support/amber-cli.js:942
                throw error;
                ^

TypeError: Cannot read property 'constructor' of null
    at Object.PrimitivesBrik.st.readJSObject (/home/adrian/.npm-packages/lib/node_modules/amber-cli/support/amber-cli.js:808:32)
    at Object.PrimitivesBrik.st.readJSObject (/home/adrian/.npm-packages/lib/node_modules/amber-cli/support/amber-cli.js:814:43)
    at Object.PrimitivesBrik.st.readJSObject (/home/adrian/.npm-packages/lib/node_modules/amber-cli/support/amber-cli.js:814:43)
    at $core.withContext.$ctx1.fill.anObject (/home/adrian/.npm-packages/lib/node_modules/amber-cli/support/amber-cli.js:21117:14)
    at inContext (/home/adrian/.npm-packages/lib/node_modules/amber-cli/support/amber-cli.js:949:26)
    at Object.RuntimeBrik.st.withContext (/home/adrian/.npm-packages/lib/node_modules/amber-cli/support/amber-cli.js:928:24)
    at $core.addMethod.$core.method.fn (/home/adrian/.npm-packages/lib/node_modules/amber-cli/support/amber-cli.js:21116:14)
    at $core.withContext.$ctx1.fill.aString (/home/adrian/.npm-packages/lib/node_modules/amber-cli/support/amber-cli.js:64720:33)
    at inContext (/home/adrian/.npm-packages/lib/node_modules/amber-cli/support/amber-cli.js:949:26)
    at Object.RuntimeBrik.st.withContext (/home/adrian/.npm-packages/lib/node_modules/amber-cli/support/amber-cli.js:928:24)
```

**Comment by herby** [comment]
Well, you can see it is in readJSObject. It comes from support/boot.js, where it is clear there is no check for nulliness, so one should add initial line like `if (js == null) return js;` (to return proper `nil` it would need more changes and `null` / `undefined` are treated as `nil` by Amber anyway, so this is probably the minimal change).

**Comment by adrian-castravete** [comment]
Hmm, I thought it went in the grunt-init package and discovered some null stuff there that was supposed to be an object... Let's see... maybe I can fix this one.

**Comment by herby** [comment]
Nevertheless, readJSObject should be null-aware, anyway. I am surprised no one was hurt by that yet...

Adrian Castravete wrote:

**Comment by adrian-castravete** [comment]
Thanks for the hints. Closing this issue :)
